/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Brett
 */
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Group1 extends javax.swing.JFrame {

    /**
     * Creates new form Group1
     */
    public Group1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        instruction1 = new javax.swing.JLabel();
        instruction2 = new javax.swing.JLabel();
        ending1 = new javax.swing.JLabel();
        ending2 = new javax.swing.JLabel();
        ending3 = new javax.swing.JLabel();
        ending4 = new javax.swing.JLabel();
        ending5 = new javax.swing.JLabel();
        ending6 = new javax.swing.JLabel();
        tip1 = new javax.swing.JLabel();
        tip2 = new javax.swing.JLabel();
        examples = new javax.swing.JLabel();
        example1 = new javax.swing.JLabel();
        example2 = new javax.swing.JLabel();
        example3 = new javax.swing.JLabel();
        example4 = new javax.swing.JLabel();
        example5 = new javax.swing.JLabel();
        practices = new javax.swing.JLabel();
        practice1 = new javax.swing.JLabel();
        practice2 = new javax.swing.JLabel();
        practice3 = new javax.swing.JLabel();
        practice4 = new javax.swing.JLabel();
        practice5 = new javax.swing.JLabel();
        practiceA1 = new javax.swing.JTextField();
        practiceA2 = new javax.swing.JTextField();
        practiceA3 = new javax.swing.JTextField();
        practiceA4 = new javax.swing.JTextField();
        practiceA5 = new javax.swing.JTextField();
        g1CheckAns = new javax.swing.JButton();
        g1Proceed = new javax.swing.JButton();
        checkOrX1 = new javax.swing.JLabel();
        checkOrX2 = new javax.swing.JLabel();
        checkOrX3 = new javax.swing.JLabel();
        checkOrX4 = new javax.swing.JLabel();
        checkOrX5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        instruction1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        instruction1.setText("To form the imparfait for 1st group verbs, simply take the radical of the verb");

        instruction2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        instruction2.setText("conjugated with \"nous\" in the present tense, and add the following endings: ");

        ending1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ending1.setText("Je: ais");

        ending2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ending2.setText("Tu: ais");

        ending3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ending3.setText("il: ait");

        ending4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ending4.setText("Nous: ions");

        ending5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ending5.setText("Vous: iez");

        ending6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ending6.setText("Ils/elles: aient");

        tip1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tip1.setText("Remember: je, tu, il and ils/elles require an e after a g to keep it soft");

        tip2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tip2.setText("They also require a \"ç\" to keep the soft c sound.");

        examples.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        examples.setText("Example: ");

        example1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        example1.setText("manger (je): [mange]ais");

        example2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        example2.setText("parler (nous): [parl]ions");

        example3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        example3.setText("commencer (il): [commenç]ait");

        example4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        example4.setText("ranger (vous): [rang]iez");

        example5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        example5.setText("accepter (ils): [accept]aient");

        practices.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        practices.setText("Try it: ");

        practice1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        practice1.setText("regarder (il): ");

        practice2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        practice2.setText("apporter (nous): ");

        practice3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        practice3.setText("songer (tu): ");

        practice4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        practice4.setText("avaler (elles): ");

        practice5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        practice5.setText("avancer (j'): ");

        g1CheckAns.setText("Check Answers");
        g1CheckAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g1CheckAnsActionPerformed(evt);
            }
        });

        g1Proceed.setText("Proceed");
        g1Proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g1ProceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(examples, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tip2))
                            .addComponent(example1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(practices)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(practice2)
                                    .addComponent(practice1)
                                    .addComponent(practice5)
                                    .addComponent(practice4)
                                    .addComponent(practice3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(practiceA4, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(practiceA5)
                                    .addComponent(practiceA2)
                                    .addComponent(practiceA1)
                                    .addComponent(practiceA3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(g1CheckAns)
                                    .addComponent(g1Proceed))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tip1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(checkOrX1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(example2)
                                        .addComponent(example3)
                                        .addComponent(example4)
                                        .addComponent(example5))
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkOrX5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(checkOrX4, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                            .addComponent(checkOrX3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(checkOrX2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ending2)
                    .addComponent(ending1)
                    .addComponent(ending3))
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ending5)
                    .addComponent(ending4)
                    .addComponent(ending6))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instruction2)
                    .addComponent(instruction1))
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instruction1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instruction2)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ending1)
                    .addComponent(ending4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ending2)
                    .addComponent(ending5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ending3)
                    .addComponent(ending6))
                .addGap(18, 18, 18)
                .addComponent(tip1)
                .addGap(4, 4, 4)
                .addComponent(tip2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(examples)
                    .addComponent(practices))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(example1))
                    .addComponent(checkOrX1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(practice1)
                        .addComponent(practiceA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkOrX2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(example2)
                        .addComponent(practice2)
                        .addComponent(practiceA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(g1CheckAns)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkOrX3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(example3)
                                .addComponent(practice3)
                                .addComponent(practiceA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkOrX4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(example4)
                                .addComponent(practice4)
                                .addComponent(practiceA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkOrX5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(example5)
                                .addComponent(practice5)
                                .addComponent(practiceA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(g1Proceed)
                        .addGap(158, 158, 158))))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Quit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Help");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void g1CheckAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g1CheckAnsActionPerformed
        /* ArrayLists to record user guesses and correct answers */
        ArrayList answers = new ArrayList();
        ArrayList guesses = new ArrayList();
        ArrayList userGuess = new ArrayList();
        
        JLabel[] checkOrX = new JLabel[5];      //checkmark or x icons
        
        /* get checkmark and x images */
        ImageIcon checkMark = new ImageIcon(getClass().getResource("/checkmark.gif"));
        ImageIcon incorrect = new ImageIcon(getClass().getResource("/incorrect.png"));

        /* correct answers */
        answers.add("regardait");
        answers.add("apportions");
        answers.add("songeais");
        answers.add("avalaient");
        answers.add("avançais");

        /* ArrayList of text fields where user guesses will be inputted */ 
        guesses.add(practiceA1.getText());
        guesses.add(practiceA2.getText());
        guesses.add(practiceA3.getText());
        guesses.add(practiceA4.getText());
        guesses.add(practiceA5.getText());

        /* labels for checkmark and x icons */
        checkOrX[0] = checkOrX1;
        checkOrX[1] = checkOrX2;
        checkOrX[2] = checkOrX3;
        checkOrX[3] = checkOrX4;
        checkOrX[4] = checkOrX5;

        for (int i = 0; i < guesses.size(); i++) {
            userGuess.add(guesses.get(i));      //get each answer from user

            if (userGuess.get(i).equals(answers.get(i))) {      //guess matches correct answer?
                checkOrX[i].setIcon(checkMark);     //display checkmark beside correct answer               
            } else {
                checkOrX[i].setText(answers.get(i).toString());     //display correct answer
                checkOrX[i].setIcon(incorrect);     //display x beside incorrect answer 
            }
        }
    
    }//GEN-LAST:event_g1CheckAnsActionPerformed

    private void g1ProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g1ProceedActionPerformed
        /* proceed to next frame (group1quiz) */
        new Group1Quiz().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_g1ProceedActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);     //close the program
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.out.println("Fill in the empty check boxes, then verify your answers."       //help
                + " next, click 'proceed'.");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                





}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Group1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 





catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Group1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 





catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Group1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 





catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Group1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Group1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkOrX1;
    private javax.swing.JLabel checkOrX2;
    private javax.swing.JLabel checkOrX3;
    private javax.swing.JLabel checkOrX4;
    private javax.swing.JLabel checkOrX5;
    private javax.swing.JLabel ending1;
    private javax.swing.JLabel ending2;
    private javax.swing.JLabel ending3;
    private javax.swing.JLabel ending4;
    private javax.swing.JLabel ending5;
    private javax.swing.JLabel ending6;
    private javax.swing.JLabel example1;
    private javax.swing.JLabel example2;
    private javax.swing.JLabel example3;
    private javax.swing.JLabel example4;
    private javax.swing.JLabel example5;
    private javax.swing.JLabel examples;
    private javax.swing.JButton g1CheckAns;
    private javax.swing.JButton g1Proceed;
    private javax.swing.JLabel instruction1;
    private javax.swing.JLabel instruction2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel practice1;
    private javax.swing.JLabel practice2;
    private javax.swing.JLabel practice3;
    private javax.swing.JLabel practice4;
    private javax.swing.JLabel practice5;
    private javax.swing.JTextField practiceA1;
    private javax.swing.JTextField practiceA2;
    private javax.swing.JTextField practiceA3;
    private javax.swing.JTextField practiceA4;
    private javax.swing.JTextField practiceA5;
    private javax.swing.JLabel practices;
    private javax.swing.JLabel tip1;
    private javax.swing.JLabel tip2;
    // End of variables declaration//GEN-END:variables
}
